import type { Metadata } from "next";
import Image from "next/image";
import '../globals.css'

export const metadata: Metadata = {
  title: "Home",
  description: "Generated by LIKEGRAVITY",
};

export default function HomeDetails(){
  return (
    <div className="flex flex-row items-center justify-between w=auto h=auto p-4">
      <div>
      <Image alt="Sircle" src="/svgs/sircle_logo.svg" width={123} height={36} priority={true} />
      </div>

      <div>
        <Image alt="Add Sircle" src="/svgs/add.svg" width={24} height={24} />
      </div>
    </div>

  );
}