import type { Metadata } from "next";
import '../globals.css'

export const metadata: Metadata = {
  title: "Home",
  description: "Generated by LIKEGRAVITY",
};

export default function HomeDetails(){
  return (
    <div className="grid grid-cols-2 top-4 left-0 right-0">
      <h1 className="flex mt-10 items-center px-4 font-bold text-xl">   
        Sircle
      </h1>
      <h1 className="flex mt-10 justify-end px-4 font-bold">
        +
      </h1>
    </div>
  );
}